#!/usr/bin/env bash
#
# sync-to-mobile.sh
#
# Builds terraso-client-shared and syncs the compiled output to the
# terraso-mobile-client's node_modules, enabling local development without
# needing to commit/push changes and run npm install in the mobile client.
#
# Symlinks don't work because Expo/Metro rejects them for security reasons,
# so this script uses rsync to copy the built files instead.
#
# Usage:
#   npm run sync-to-mobile         # One-time build and sync
#   npm run sync-to-mobile:watch   # Watch mode: auto-rebuild on source changes
#
# Watch mode also detects when npm install overwrites the synced files
#
# Note: Requires chokidar-cli for watch mode (included in devDependencies).
#
set -e

###############################################
# CONFIG
###############################################
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET="$LIB_ROOT/../terraso-mobile-client/dev-client/node_modules/terraso-client-shared"
TARGET_PARENT="$(dirname "$TARGET")"
RETRY_DELAY=10 # seconds to wait before retrying if npm install is in progress
MAX_RETRIES=30 # max retries (~5 minutes total wait for npm install)

###############################################
# WAIT FOR NPM INSTALL FUNCTION
###############################################
wait_for_npm_install() {
  local retries=0
  while [[ $retries -lt $MAX_RETRIES ]]; do
    # Ready if node_modules exists and .package-lock.json exists (npm install finished)
    if [[ -d "$TARGET_PARENT" ]] && [[ -f "$TARGET_PARENT/.package-lock.json" ]]; then
      return 0
    fi
    echo "⏳ Waiting for npm install to complete... (${retries}/${MAX_RETRIES})"
    sleep "$RETRY_DELAY"
    ((retries++))
  done
  echo "⚠️  Timed out waiting for npm install"
  return 1
}

###############################################
# BUILD & SYNC FUNCTION
###############################################
build_and_sync() {
  # Wait for npm install to complete (with retry)
  if ! wait_for_npm_install; then
    return 1
  fi

  echo "🔨 Building terraso-client-shared..."
  cd "$LIB_ROOT"
  npm run build

  echo "📄 Syncing to mobile client node_modules..."
  mkdir -p "$TARGET"
  rsync -av --delete \
    --exclude=node_modules \
    --exclude=.git \
    --exclude=.husky \
    "$LIB_ROOT/dist/" \
    "$TARGET/"

  # Copy assets to root level, mimicking what scripts/prepare.sh does when
  # this package is installed as a dependency (look for "cp -r src/assets .")
  cp -r "$LIB_ROOT/src/assets" "$TARGET/"

  echo "✅ Sync complete at $(date '+%H:%M:%S')"
}

###############################################
# MAIN LOGIC
###############################################
if [[ "$1" == "--watch" || "$1" == "-w" ]]; then
  echo "🔄 Watch mode enabled"
  build_and_sync

  # Watch source files and node_modules/.package-lock.json (to detect npm install)
  # Ignore src/graphqlSchema which is generated by 'npm run build' (via generate-types)
  npx chokidar \
    "$LIB_ROOT/src/**/*" \
    "$TARGET_PARENT/.package-lock.json" \
    --ignore "$LIB_ROOT/src/graphqlSchema/**" \
    --debounce 500 \
    -c "$0"
else
  build_and_sync
fi
