name: Update Shared Client Version

on:
  workflow_call:
    inputs:
      repo-path:
        required: true
        type: string
      repo-ref:
        required: true
        type: string
      working-directory:
        required: false
        type: string
      cache-dependency-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  update-web:
    runs-on: ubuntu-latest

    steps:
      - name: Check out dependent Git repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo-path }}
          ref: ${{ inputs.repo-ref }}
          token: ${{ secrets.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm install "github:techmatters/terraso-client-shared#${{ env.client_hash }}"
          npm install

      - name: Commit version bump
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "build: update shared client to ${{ env.client_hash }}"
          git push
